spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.zqindmcmmrlhtovgitkd&password=${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086

